#!/usr/bin/env python3
"""Generate report.md: a single deterministic summary of repository state.

The pattern is taken from karpathy/nanochat (MIT, 92d63d4e) — one generated Markdown file
summarising a run, useful as an audit trail and as a feedback loop for an agent that needs
the state of the tree without running five commands.

DETERMINISM IS THE POINT. The output contains no timestamps, durations, hostnames, run
identifiers or absolute paths: regenerating on an unchanged tree produces a byte-identical
file. This is not fussiness. The `posture` workflow already carries a warning about
implementing the secret scan as `scan --baseline` plus `git diff --exit-code`, because that
rewrites a timestamp on every run and so fails when nothing is wrong. A report with a
timestamp has
the same shape: every run produces a diff, the diff stops carrying information, and
reviewers learn to ignore the file.

Because it is deterministic, staleness is checkable:

    python3 .runwai/tools/report.py            # write report.md
    python3 .runwai/tools/report.py --check    # exit 1 if the committed report is stale

Exit codes:
    0  written, or (with --check) up to date
    1  stale (--check only)
    2  could not run
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

MD_LINK = re.compile(r"\[[^\]]*\]\(([^)\s]+)\)")
PROVENANCE_ROW = re.compile(r"^\|\s*`([^`]+)`\s*\|\s*`([0-9a-f]{40})`\s*\|\s*([^|]+?)\s*\|", re.M)


def run(cmd: list[str], root: Path) -> tuple[int, str]:
    """Run a self-check, returning its exit code and final summary line."""
    try:
        proc = subprocess.run(  # nosec B603 - fixed argv, no shell, no user input
            cmd, cwd=root, capture_output=True, text=True, timeout=300
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return 2, f"could not run: {type(exc).__name__}"
    lines = [ln for ln in proc.stdout.splitlines() if ln.strip()]
    summary = ""
    for line in reversed(lines):
        if line.startswith(("runwai-", "PASSED", "FAILED")):
            summary = line if not line.startswith(("PASSED", "FAILED")) else summary
            if summary:
                break
    return proc.returncode, summary or (lines[-1] if lines else "no output")


def verdict(code: int) -> str:
    return {0: "pass", 1: "**fail**"}.get(code, "**could not run**")


def count_dir(root: Path, rel: str, pattern: str, skip_meta: bool = True) -> int:
    target = root / rel
    if not target.is_dir():
        return 0
    return sum(
        1 for p in target.glob(pattern)
        if p.is_file() and not (skip_meta and p.name.startswith("_")) and p.name != "README.md"
    )


def count_decisions(root: Path) -> int:
    """Count records in .runwai/decisions.yaml without a YAML parser.

    report.py already depends on pyyaml through the checks it shells out to, but the
    count is one line-anchored match and reading it this way keeps report.py runnable on
    a bare interpreter, which is what makes the FATAL above the only setup error.
    """
    path = root / ".runwai" / "decisions.yaml"
    if not path.is_file():
        return 0
    return len(re.findall(r"^  - id:", path.read_text(encoding="utf-8"), re.M))


def provenance_rows(root: Path) -> list[tuple[str, str, str]]:
    path = root / ".runwai" / "provenance.md"
    if not path.is_file():
        return []
    return [
        (repo, sha[:12], lic.replace("**", "").strip())
        for repo, sha, lic in PROVENANCE_ROW.findall(path.read_text(encoding="utf-8"))
    ]


def build(root: Path) -> str:
    registry_code, registry_summary = run(
        [sys.executable, ".runwai/tools/validate_registry.py"], root
    )
    helpers_code, helpers_summary = run(
        [sys.executable, ".runwai/tools/validate_helpers.py"], root
    )

    rules = count_dir(root, "agents/rules", "*.md")
    decisions = count_decisions(root)
    skills = sum(1 for _ in (root / "agents" / "skills").glob("*/SKILL.md")) if (
        root / "agents" / "skills"
    ).is_dir() else 0
    sources = provenance_rows(root)

    out: list[str] = []
    add = out.append

    add("# runwAI report")
    add("")
    add("Generated by `python3 .runwai/tools/report.py`. Do not edit by hand.")
    add("")
    add(
        "This file is deliberately timestamp-free: regenerating it on an unchanged tree "
        "produces a byte-identical file, so a diff here means the repository actually "
        "changed. Check staleness with `python3 .runwai/tools/report.py --check`."
    )
    add("")

    add("## Self-checks")
    add("")
    add("| Check | Result | Summary |")
    add("| :--- | :--- | :--- |")
    add(f"| `.runwai/tools/validate_registry.py` | {verdict(registry_code)} | {registry_summary} |")
    add(f"| `.runwai/tools/validate_helpers.py` | {verdict(helpers_code)} | {helpers_summary} |")
    add("")
    add(
        "Warnings are expected while pins remain pending; they are reported rather than "
        "hidden. See `.runwai/pinning.md`."
    )
    add("")

    add("## Contents")
    add("")
    add("| Item | Count |")
    add("| :--- | ---: |")
    add(f"| Agent rules | {rules} |")
    add(f"| Agent skills | {skills} |")
    add(f"| Template decisions recorded | {decisions} |")
    add("")

    add("## Vendored sources")
    add("")
    if sources:
        add(
            f"{len(sources)} upstream sources, each resolved to a full commit SHA with its "
            "licence read from the upstream tree. Full detail in "
            "`.runwai/provenance.md`."
        )
        add("")
        add("| Source | Commit | Licence |")
        add("| :--- | :--- | :--- |")
        for repo, sha, lic in sources:
            add(f"| `{repo}` | `{sha}` | {lic} |")
    else:
        add("No provenance record found.")
    add("")

    add("---")
    add("")
    add(
        "Nothing in this report is a compliance claim. It records what is present and "
        "whether the structural self-checks pass — not whether any control is effective."
    )
    add("")

    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=".", type=Path)
    parser.add_argument(
        "--check", action="store_true", help="fail if the committed report is stale"
    )
    args = parser.parse_args()

    root = args.repo_root.resolve()
    if not (root / ".runwai" / "tools").is_dir():
        print(
            "FATAL: no .runwai/tools/ directory; is --repo-root correct?", file=sys.stderr
        )
        return 2

    content = build(root)
    path = root / "report.md"

    if args.check:
        if not path.is_file():
            print("FAILED: report.md does not exist. Run: python3 .runwai/tools/report.py")
            return 1
        if path.read_text(encoding="utf-8") != content:
            print(
                "FAILED: report.md is stale. Run `python3 .runwai/tools/report.py` and commit "
                "the result."
            )
            return 1
        print("report.md is up to date")
        return 0

    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
